
package Principal;

import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.concurrent.Semaphore;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.JPanel;

public class Principal extends javax.swing.JFrame {
    
    public static int acordado = 0;
    public static int menssage = 0;
    public static int max_id = 15;
    public static int max_msg_mailbox;
    public static Pombo pombo;
    public static ArrayList<Usuario> users = new ArrayList<Usuario>();
    public static ArrayList<JLabel> users_img = new ArrayList<JLabel>();
    public static ArrayList<JLabel> users_stats = new ArrayList<JLabel>();
    public static Mensagem mailbox_left, mailbox_rigth;
    public static Semaphore viajar = new Semaphore(0);
    public static Semaphore mutex_acordado = new Semaphore(1);
    public static Semaphore mutex_menssage = new Semaphore(1);
    
    /**
     * Creates new form PrincipalFrame
     */
    public Principal() {
        getMaxMsg();
        mailbox_left = new Mensagem(max_msg_mailbox);
        mailbox_rigth = new Mensagem(Integer.MAX_VALUE);
        initComponents();
        configure_JLabels();
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_aside_left = new javax.swing.JPanel();
        jbutton_new_pombo = new javax.swing.JButton();
        jbutton_new_user = new javax.swing.JButton();
        jbutton_del_pombo = new javax.swing.JButton();
        jbutton_del_user = new javax.swing.JButton();
        jpanel_user = new javax.swing.JPanel();
        user1 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        user3 = new javax.swing.JLabel();
        user4 = new javax.swing.JLabel();
        user5 = new javax.swing.JLabel();
        user6 = new javax.swing.JLabel();
        user7 = new javax.swing.JLabel();
        user8 = new javax.swing.JLabel();
        user9 = new javax.swing.JLabel();
        user10 = new javax.swing.JLabel();
        user11 = new javax.swing.JLabel();
        user12 = new javax.swing.JLabel();
        user13 = new javax.swing.JLabel();
        user14 = new javax.swing.JLabel();
        user15 = new javax.swing.JLabel();
        user1_status = new javax.swing.JLabel();
        user2_status = new javax.swing.JLabel();
        user3_status = new javax.swing.JLabel();
        user4_status = new javax.swing.JLabel();
        user5_status = new javax.swing.JLabel();
        user6_status = new javax.swing.JLabel();
        user7_status = new javax.swing.JLabel();
        user8_status = new javax.swing.JLabel();
        user9_status = new javax.swing.JLabel();
        user10_status = new javax.swing.JLabel();
        user11_status = new javax.swing.JLabel();
        user12_status = new javax.swing.JLabel();
        user13_status = new javax.swing.JLabel();
        user14_status = new javax.swing.JLabel();
        user15_status = new javax.swing.JLabel();
        jpanel_exec = new javax.swing.JPanel();
        img_mailbox_left = new javax.swing.JLabel();
        img_mailbox_right = new javax.swing.JLabel();
        img_pombo = new javax.swing.JLabel();
        qtd_msg_mailA = new javax.swing.JLabel();
        label_msg_1 = new javax.swing.JLabel();
        qtd_msg_mailB = new javax.swing.JLabel();
        label_msg_2 = new javax.swing.JLabel();
        jpanel_log = new javax.swing.JPanel();
        label_stats_pombo = new javax.swing.JLabel();
        status_pombo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa S.O.");

        jpanel_aside_left.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciador de Processos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 0, 12))); // NOI18N

        jbutton_new_pombo.setText("Criar Pombo");
        jbutton_new_pombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_new_pomboActionPerformed(evt);
            }
        });

        jbutton_new_user.setText("Criar Usuário");
        jbutton_new_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_new_userActionPerformed(evt);
            }
        });

        jbutton_del_pombo.setText("Excluir Pombo");
        jbutton_del_pombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_del_pomboActionPerformed(evt);
            }
        });

        jbutton_del_user.setText("Excluir Usuário");
        jbutton_del_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_del_userActionPerformed(evt);
            }
        });

        jpanel_user.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciado de Usuarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 0, 12))); // NOI18N
        jpanel_user.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N

        user1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user64.png"))); // NOI18N

        user1_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1_status.setText("Escrevendo");

        user2_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user2_status.setText("Escrevendo");

        user3_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user3_status.setText("Escrevendo");

        user4_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user4_status.setText("Escrevendo");

        user5_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user5_status.setText("Escrevendo");

        user6_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user6_status.setText("Escrevendo");

        user7_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user7_status.setText("Escrevendo");

        user8_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user8_status.setText("Escrevendo");

        user9_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user9_status.setText("Escrevendo");

        user10_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user10_status.setText("Escrevendo");

        user11_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user11_status.setText("Escrevendo");

        user12_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user12_status.setText("Escrevendo");

        user13_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user13_status.setText("Escrevendo");

        user14_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user14_status.setText("Escrevendo");

        user15_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user15_status.setText("Escrevendo");

        javax.swing.GroupLayout jpanel_userLayout = new javax.swing.GroupLayout(jpanel_user);
        jpanel_user.setLayout(jpanel_userLayout);
        jpanel_userLayout.setHorizontalGroup(
            jpanel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_userLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_userLayout.createSequentialGroup()
                        .addComponent(user1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user5))
                    .addGroup(jpanel_userLayout.createSequentialGroup()
                        .addComponent(user6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user10))
                    .addGroup(jpanel_userLayout.createSequentialGroup()
                        .addComponent(user14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user11))
                    .addGroup(jpanel_userLayout.createSequentialGroup()
                        .addComponent(user1_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user2_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user4_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user3_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user5_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_userLayout.createSequentialGroup()
                        .addComponent(user10_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user9_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user8_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user7_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user6_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_userLayout.createSequentialGroup()
                        .addComponent(user15_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user12_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user13_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user14_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user11_status, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpanel_userLayout.setVerticalGroup(
            jpanel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_userLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user5)
                    .addComponent(user4)
                    .addComponent(user3)
                    .addComponent(user2)
                    .addComponent(user1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user1_status)
                    .addComponent(user2_status)
                    .addComponent(user4_status)
                    .addComponent(user3_status)
                    .addComponent(user5_status))
                .addGap(18, 18, 18)
                .addGroup(jpanel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user10)
                    .addComponent(user9)
                    .addComponent(user8)
                    .addComponent(user7)
                    .addComponent(user6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user10_status)
                    .addComponent(user9_status)
                    .addComponent(user8_status)
                    .addComponent(user7_status)
                    .addComponent(user6_status))
                .addGap(17, 17, 17)
                .addGroup(jpanel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(user11)
                        .addComponent(user15)
                        .addComponent(user13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user15_status)
                    .addComponent(user12_status)
                    .addComponent(user13_status)
                    .addComponent(user14_status)
                    .addComponent(user11_status)))
        );

        javax.swing.GroupLayout jpanel_aside_leftLayout = new javax.swing.GroupLayout(jpanel_aside_left);
        jpanel_aside_left.setLayout(jpanel_aside_leftLayout);
        jpanel_aside_leftLayout.setHorizontalGroup(
            jpanel_aside_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_aside_leftLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jpanel_aside_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbutton_new_pombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbutton_del_pombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jpanel_aside_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbutton_del_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbutton_new_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
            .addComponent(jpanel_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanel_aside_leftLayout.setVerticalGroup(
            jpanel_aside_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_aside_leftLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpanel_aside_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutton_new_user)
                    .addComponent(jbutton_new_pombo))
                .addGap(36, 36, 36)
                .addGroup(jpanel_aside_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutton_del_pombo)
                    .addComponent(jbutton_del_user))
                .addGap(18, 18, 18)
                .addComponent(jpanel_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanel_exec.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espaço de Execução", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 0, 12))); // NOI18N

        img_mailbox_left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mailboxA.png"))); // NOI18N

        img_mailbox_right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mailboxB.png"))); // NOI18N

        img_pombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dove64.png"))); // NOI18N
        img_pombo.setEnabled(false);

        qtd_msg_mailA.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        qtd_msg_mailA.setText("0");

        label_msg_1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        label_msg_1.setText("msg's");

        qtd_msg_mailB.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        qtd_msg_mailB.setText("0");

        label_msg_2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        label_msg_2.setText("msg's");

        javax.swing.GroupLayout jpanel_execLayout = new javax.swing.GroupLayout(jpanel_exec);
        jpanel_exec.setLayout(jpanel_execLayout);
        jpanel_execLayout.setHorizontalGroup(
            jpanel_execLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_execLayout.createSequentialGroup()
                .addGroup(jpanel_execLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_execLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(img_mailbox_left, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                        .addComponent(img_mailbox_right, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_execLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(img_pombo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpanel_execLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(qtd_msg_mailA)
                .addGap(18, 18, 18)
                .addComponent(label_msg_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(qtd_msg_mailB)
                .addGap(18, 18, 18)
                .addComponent(label_msg_2)
                .addGap(17, 17, 17))
        );
        jpanel_execLayout.setVerticalGroup(
            jpanel_execLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_execLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_pombo)
                .addGap(18, 18, 18)
                .addGroup(jpanel_execLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(img_mailbox_left)
                    .addComponent(img_mailbox_right))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanel_execLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_execLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qtd_msg_mailB)
                        .addComponent(label_msg_2))
                    .addGroup(jpanel_execLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qtd_msg_mailA)
                        .addComponent(label_msg_1)))
                .addContainerGap())
        );

        jpanel_log.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Painel de Atividades", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 0, 12))); // NOI18N

        label_stats_pombo.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        label_stats_pombo.setText("Status Pombo:");

        status_pombo.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        status_pombo.setText("Pombo não foi criado...");

        javax.swing.GroupLayout jpanel_logLayout = new javax.swing.GroupLayout(jpanel_log);
        jpanel_log.setLayout(jpanel_logLayout);
        jpanel_logLayout.setHorizontalGroup(
            jpanel_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_logLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_stats_pombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status_pombo)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jpanel_logLayout.setVerticalGroup(
            jpanel_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_logLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_stats_pombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status_pombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_aside_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel_exec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanel_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpanel_aside_left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanel_exec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jpanel_log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton_new_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_new_userActionPerformed
        // TODO add your handling code here:
        create_new_user(); 
    }//GEN-LAST:event_jbutton_new_userActionPerformed

    private void jbutton_new_pomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_new_pomboActionPerformed
        // TODO add your handling code here:
        create_new_pombo();
    }//GEN-LAST:event_jbutton_new_pomboActionPerformed

    private void jbutton_del_pomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_del_pomboActionPerformed
        // TODO add your handling code here:
        delete_pombo();
    }//GEN-LAST:event_jbutton_del_pomboActionPerformed

    private void jbutton_del_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_del_userActionPerformed
        // TODO add your handling code here:
        delete_user();
    }//GEN-LAST:event_jbutton_del_userActionPerformed
    
    private void getMaxMsg(){
        boolean exit = false;
        boolean exit_program = false;
        JFormattedTextField jftf_max = new JFormattedTextField();
        jftf_max.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftf_max.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Object[] body = {
            "Digite a quantidade máxima de mensagens que serão armazenadas na caixa:",
            jftf_max
        };
        while(!exit){
            int entrada = JOptionPane.showConfirmDialog (null, body,"Programa S.O.",OK_CANCEL_OPTION,PLAIN_MESSAGE);
            if(entrada == JOptionPane.OK_OPTION){
                max_msg_mailbox = parseInt(jftf_max.getText());
                exit = true;
            }
            else{ exit = true; exit_program = true;}
        }
        
        if(exit_program){ System.exit(0); }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal();
        });
    }
    
    public static void upViajar(){
        viajar.release();
    }
    
    public static void downViajar(){
        try{
            viajar.acquire();
        } catch(InterruptedException e){}
    }
    
    public static void upMutex_acordado(){
        mutex_acordado.release();
    }
    
    public static void downMutex_acordado(){
        try{
            mutex_acordado.acquire();
        } catch(InterruptedException e){}
    }
    
    public static void upMutex_menssage(){
        mutex_menssage.release();
    }
    
    public static void downMutex_menssage(){
        try{
            mutex_menssage.acquire();
        } catch(InterruptedException e){}
    }
    
    //ATÉ AQUI

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_mailbox_left;
    private javax.swing.JLabel img_mailbox_right;
    public static javax.swing.JLabel img_pombo;
    private javax.swing.JButton jbutton_del_pombo;
    private javax.swing.JButton jbutton_del_user;
    private javax.swing.JButton jbutton_new_pombo;
    private javax.swing.JButton jbutton_new_user;
    private javax.swing.JPanel jpanel_aside_left;
    private javax.swing.JPanel jpanel_exec;
    private javax.swing.JPanel jpanel_log;
    private javax.swing.JPanel jpanel_user;
    private javax.swing.JLabel label_msg_1;
    private javax.swing.JLabel label_msg_2;
    private javax.swing.JLabel label_stats_pombo;
    public static javax.swing.JLabel qtd_msg_mailA;
    public static javax.swing.JLabel qtd_msg_mailB;
    public static javax.swing.JLabel status_pombo;
    public static javax.swing.JLabel user1;
    public static javax.swing.JLabel user10;
    public static javax.swing.JLabel user10_status;
    public static javax.swing.JLabel user11;
    public static javax.swing.JLabel user11_status;
    public static javax.swing.JLabel user12;
    public static javax.swing.JLabel user12_status;
    public static javax.swing.JLabel user13;
    public static javax.swing.JLabel user13_status;
    public static javax.swing.JLabel user14;
    public static javax.swing.JLabel user14_status;
    public static javax.swing.JLabel user15;
    public static javax.swing.JLabel user15_status;
    public static javax.swing.JLabel user1_status;
    public static javax.swing.JLabel user2;
    public static javax.swing.JLabel user2_status;
    public static javax.swing.JLabel user3;
    public static javax.swing.JLabel user3_status;
    public static javax.swing.JLabel user4;
    public static javax.swing.JLabel user4_status;
    public static javax.swing.JLabel user5;
    public static javax.swing.JLabel user5_status;
    public static javax.swing.JLabel user6;
    public static javax.swing.JLabel user6_status;
    public static javax.swing.JLabel user7;
    public static javax.swing.JLabel user7_status;
    public static javax.swing.JLabel user8;
    public static javax.swing.JLabel user8_status;
    public static javax.swing.JLabel user9;
    public static javax.swing.JLabel user9_status;
    // End of variables declaration//GEN-END:variables
    
    private void configure_JLabels(){
        users_img.add(user1);
        users_img.add(user2);
        users_img.add(user3);
        users_img.add(user4);
        users_img.add(user5);
        users_img.add(user6);
        users_img.add(user7);
        users_img.add(user8);
        users_img.add(user9);
        users_img.add(user10);
        users_img.add(user11);
        users_img.add(user12);
        users_img.add(user13);
        users_img.add(user14);
        users_img.add(user15);
        users_img.forEach((img) -> { img.setEnabled(false); });
        
        users_stats.add(user1_status);
        users_stats.add(user2_status);
        users_stats.add(user3_status);
        users_stats.add(user4_status);
        users_stats.add(user5_status);
        users_stats.add(user6_status);
        users_stats.add(user7_status);
        users_stats.add(user8_status);
        users_stats.add(user9_status);
        users_stats.add(user10_status);
        users_stats.add(user11_status);
        users_stats.add(user12_status);
        users_stats.add(user13_status);
        users_stats.add(user14_status);
        users_stats.add(user15_status);
        users_stats.forEach( (status) -> { status.setText(""); } );
        
        for(int i=0; i<max_id; i++){
            users.add(null);
        }
        
    }
    
    private void create_new_user(){
        // <editor-fold defaultstate="collapsed" desc="JPanel Code">
        JPanel jpanel_new_user = new javax.swing.JPanel();
        JLabel label_criar_usuario = new javax.swing.JLabel();
        JLabel label_img = new javax.swing.JLabel();
        JLabel label_id = new javax.swing.JLabel();
        JLabel label_te = new javax.swing.JLabel();
        JFormattedTextField jftf_id = new javax.swing.JFormattedTextField();
        JFormattedTextField jftf_te = new javax.swing.JFormattedTextField();

        label_criar_usuario.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        label_criar_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_criar_usuario.setText("Criar Usuário");

        label_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/userAdd32.png"))); // NOI18N

        label_id.setText("ID:");

        label_te.setText("Tempo de escrita:");
        
        jftf_id.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftf_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jftf_te.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jftf_te.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        
        javax.swing.GroupLayout jpanel_new_userLayout = new javax.swing.GroupLayout(jpanel_new_user);
        jpanel_new_user.setLayout(jpanel_new_userLayout);
        jpanel_new_userLayout.setHorizontalGroup(
            jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_new_userLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_new_userLayout.createSequentialGroup()
                        .addComponent(label_id)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_id))
                    .addGroup(jpanel_new_userLayout.createSequentialGroup()
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addComponent(label_img)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_criar_usuario)
                        .addGap(46, 46, 46))
                    .addGroup(jpanel_new_userLayout.createSequentialGroup()
                        .addComponent(label_te)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_te)))
                .addContainerGap())
        );
        jpanel_new_userLayout.setVerticalGroup(
            jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_new_userLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_criar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_img))
                .addGap(30, 30, 30)
                .addGroup(jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(jftf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_te)
                    .addComponent(jftf_te, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        ); //</editor-fold>
        boolean exit = false;
        while(!exit){
            int entrada = JOptionPane.showConfirmDialog (null,jpanel_new_user,"Criando Usuário",OK_CANCEL_OPTION,PLAIN_MESSAGE);
            if(entrada == JOptionPane.OK_OPTION){
                int id = parseInt(jftf_id.getText());
                float te = parseFloat(jftf_te.getText().replace(',', '.'));

                Usuario temp_user = new Usuario(id, te);
                users.set(id-1, temp_user);
                temp_user.start();
                exit = true;
            }
            else{ exit = true; }
        }
        
    }

    private void create_new_pombo(){
        // <editor-fold defaultstate="collapsed" desc="JPanel Code">
        JPanel jpanel_new_pombo = new javax.swing.JPanel();
        JLabel label_criarpombo = new javax.swing.JLabel();
        JLabel np_img_pombo = new javax.swing.JLabel();
        JLabel label_qtd_msg = new javax.swing.JLabel();
        JLabel label_tc = new javax.swing.JLabel();
        JLabel label_tv = new javax.swing.JLabel();
        JLabel label_td = new javax.swing.JLabel();
        JFormattedTextField jftf_msg = new javax.swing.JFormattedTextField();
        JFormattedTextField jftf_tc = new javax.swing.JFormattedTextField();
        JFormattedTextField jftf_tv = new javax.swing.JFormattedTextField();
        JFormattedTextField jftf_td = new javax.swing.JFormattedTextField();
        
        label_criarpombo.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        label_criarpombo.setText("Criar Pombo");

        np_img_pombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dove32.png"))); // NOI18N

        label_qtd_msg.setText("Quantidade de Mensagens:");

        label_tc.setText("Tempo de carga:");

        label_tv.setText("Tempo de Voo:");

        label_td.setText("Tempo de descarga:");

        jftf_msg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftf_msg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jpanel_new_pomboLayout = new javax.swing.GroupLayout(jpanel_new_pombo);
        jpanel_new_pombo.setLayout(jpanel_new_pomboLayout);
        jpanel_new_pomboLayout.setHorizontalGroup(
            jpanel_new_pomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_new_pomboLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpanel_new_pomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_new_pomboLayout.createSequentialGroup()
                        .addComponent(label_qtd_msg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftf_msg))
                    .addGroup(jpanel_new_pomboLayout.createSequentialGroup()
                        .addComponent(label_tc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftf_tc))
                    .addGroup(jpanel_new_pomboLayout.createSequentialGroup()
                        .addComponent(label_tv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftf_tv))
                    .addGroup(jpanel_new_pomboLayout.createSequentialGroup()
                        .addGroup(jpanel_new_pomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_new_pomboLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(np_img_pombo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_criarpombo))
                            .addGroup(jpanel_new_pomboLayout.createSequentialGroup()
                                .addComponent(label_td)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftf_td, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpanel_new_pomboLayout.setVerticalGroup(
            jpanel_new_pomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_new_pomboLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanel_new_pomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(np_img_pombo)
                    .addComponent(label_criarpombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jpanel_new_pomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_qtd_msg)
                    .addComponent(jftf_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jpanel_new_pomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tc)
                    .addComponent(jftf_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jpanel_new_pomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tv)
                    .addComponent(jftf_tv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jpanel_new_pomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_td)
                    .addComponent(jftf_td, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );//</editor-fold>     
        boolean exit = false;
        while(!exit){
            int entrada = JOptionPane.showConfirmDialog (null,jpanel_new_pombo,"Criando Pombo",OK_CANCEL_OPTION,PLAIN_MESSAGE);
            if(entrada == JOptionPane.OK_OPTION){
                int msg = parseInt(jftf_msg.getText());
                float tv = parseFloat(jftf_tv.getText().replace(',', '.'));
                float tc = parseFloat(jftf_tc.getText().replace(',', '.'));
                float td = parseFloat(jftf_td.getText().replace(',', '.'));

                pombo = new Pombo(tc, td, tv, msg);
                pombo.start();
                exit = true;
            }
            else{ exit = true; }
        }
        
        
        
    }
    
    private void delete_user(){
        // <editor-fold defaultstate="collapsed" desc="JPanel Code">
        JPanel jpanel_del_user = new javax.swing.JPanel();
        JLabel label_del_user = new javax.swing.JLabel();
        JLabel label_img1 = new javax.swing.JLabel();
        JLabel label_id1 = new javax.swing.JLabel();
        JFormattedTextField jftf_id1 = new javax.swing.JFormattedTextField();
        
        label_del_user.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        label_del_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_del_user.setText("Excluir Usuário");

        label_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user32.png"))); // NOI18N

        label_id1.setText("ID:");

        jftf_id1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftf_id1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jpanel_del_userLayout = new javax.swing.GroupLayout(jpanel_del_user);
        jpanel_del_user.setLayout(jpanel_del_userLayout);
        jpanel_del_userLayout.setHorizontalGroup(
            jpanel_del_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_del_userLayout.createSequentialGroup()
                .addGroup(jpanel_del_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel_del_userLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(label_id1)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel_del_userLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(label_img1)
                        .addGap(18, 18, 18)
                        .addComponent(label_del_user)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jpanel_del_userLayout.setVerticalGroup(
            jpanel_del_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_del_userLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_del_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_del_user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_img1))
                .addGap(30, 30, 30)
                .addGroup(jpanel_del_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id1)
                    .addComponent(jftf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );//</editor-fold>
        boolean exit = false;
        while(!exit){
            int entrada = JOptionPane.showConfirmDialog (null,jpanel_del_user,"Excluir Usuário",OK_CANCEL_OPTION,PLAIN_MESSAGE);
            if(entrada == JOptionPane.OK_OPTION){
                int id = parseInt(jftf_id1.getText());
                users.get(id-1).excluirUsuario();
                exit = true;
            }
            else{ exit = true; }
        }
    }
    
    private void delete_pombo(){
        boolean exit = false;
        while(!exit){
            int entrada = JOptionPane.showConfirmDialog (null,"Deseja Libertar o Pombo?","Libertar Pombo",OK_CANCEL_OPTION,WARNING_MESSAGE);
            if(entrada == JOptionPane.OK_OPTION){
                pombo.libertarPombo();
                exit = true;
            }
            else{ exit = true; }
        }
    }

}
