/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

/**
 *
 * @author Ibyte
 */
public class usuarioJframe extends javax.swing.JFrame {

    /**
     * Creates new form usuarioJframe
     */
    public usuarioJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_new_user = new javax.swing.JPanel();
        label_criar_usuario = new javax.swing.JLabel();
        label_img = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        label_te = new javax.swing.JLabel();
        jftf_id = new javax.swing.JFormattedTextField();
        jftf_te = new javax.swing.JFormattedTextField();
        jpanel_del_user = new javax.swing.JPanel();
        label_del_user = new javax.swing.JLabel();
        label_img1 = new javax.swing.JLabel();
        label_id1 = new javax.swing.JLabel();
        jftf_id1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_criar_usuario.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        label_criar_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_criar_usuario.setText("Criar Usuário");

        label_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/userAdd32.png"))); // NOI18N

        label_id.setText("ID:");

        label_te.setText("Tempo de escrita:");

        jftf_id.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftf_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jftf_te.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jftf_te.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jpanel_new_userLayout = new javax.swing.GroupLayout(jpanel_new_user);
        jpanel_new_user.setLayout(jpanel_new_userLayout);
        jpanel_new_userLayout.setHorizontalGroup(
            jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_new_userLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_new_userLayout.createSequentialGroup()
                        .addComponent(label_id)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_id))
                    .addGroup(jpanel_new_userLayout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addComponent(label_img)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_criar_usuario)
                        .addGap(46, 46, 46))
                    .addGroup(jpanel_new_userLayout.createSequentialGroup()
                        .addComponent(label_te)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_te)))
                .addContainerGap())
        );
        jpanel_new_userLayout.setVerticalGroup(
            jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_new_userLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_criar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_img))
                .addGap(30, 30, 30)
                .addGroup(jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(jftf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jpanel_new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_te)
                    .addComponent(jftf_te, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        label_del_user.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        label_del_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_del_user.setText("Excluir Usuário");

        label_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user32.png"))); // NOI18N

        label_id1.setText("ID:");

        jftf_id1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftf_id1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftf_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_id1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_del_userLayout = new javax.swing.GroupLayout(jpanel_del_user);
        jpanel_del_user.setLayout(jpanel_del_userLayout);
        jpanel_del_userLayout.setHorizontalGroup(
            jpanel_del_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_del_userLayout.createSequentialGroup()
                .addGroup(jpanel_del_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel_del_userLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(label_id1)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel_del_userLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(label_img1)
                        .addGap(18, 18, 18)
                        .addComponent(label_del_user)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jpanel_del_userLayout.setVerticalGroup(
            jpanel_del_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_del_userLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_del_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_del_user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_img1))
                .addGap(30, 30, 30)
                .addGroup(jpanel_del_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id1)
                    .addComponent(jftf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel_new_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jpanel_del_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel_new_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jpanel_del_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jftf_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_id1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarioJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarioJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarioJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarioJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarioJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jftf_id;
    private javax.swing.JFormattedTextField jftf_id1;
    private javax.swing.JFormattedTextField jftf_te;
    private javax.swing.JPanel jpanel_del_user;
    private javax.swing.JPanel jpanel_new_user;
    private javax.swing.JLabel label_criar_usuario;
    private javax.swing.JLabel label_del_user;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_id1;
    private javax.swing.JLabel label_img;
    private javax.swing.JLabel label_img1;
    private javax.swing.JLabel label_te;
    // End of variables declaration//GEN-END:variables
}
